#ifndef ENUMS_H
#define ENUMS_H

enum MOUSE_REPORT {
    REPORT_CONNECTION = 0x46,
    REPORT_HARDWARE = 0x50,
    REPORT_HEARTBEAT = 0x51,
    REPORT_ONBOARD_LED_SETTINGS = 0x52
} typedef MOUSE_REPORT;

enum MOUSE_BUTTON {
	LEFT_MOUSE_BUTTON,
	RIGHT_MOUSE_BUTTON,
	MIDDLE_MOUSE_BUTTON,
	BACK_SIDE_BUTTON,
	FORWARD_SIDE_BUTTON,
	DPI_BUTTON
} typedef MOUSE_BUTTON;

enum ASSIGNMENT_TYPE {
    DISABLED_FUNCTION,
	MOUSE_FUNCTION,
	KEYBOARD_FUNCTION,
	MEDIA_FUNCTION,
	MACRO_FUNCTION,
	DPI_FUNCTION = 7
} typedef ASSIGNMENT_TYPE;

enum TYPE_MOUSE_FUNCTION {
    LEFT_CLICK = 1,
    RIGHT_CLICK,
    MIDDLE_CLICK,
    BACK,
    FORWARD
} typedef TYPE_MOUSE_FUNCTION;

enum TYPE_KEYBOARD_FUNCTION {
    KEY_A = 0x04
} typedef TYPE_KEYBOARD_FUNCTION;

enum TYPE_MEDIA_FUNCTION {
    PLAY_PAUSE  = 0x00,
    STOP        = 0x01,
    PREVIOUS    = 0x02,
    NEXT        = 0x03,
    MUTE        = 0x04,
    VOLUME_DOWN = 0x05,
    VOLUME_UP   = 0x06,
} typedef TYPE_MEDIA_FUNCTION;

enum TYPE_DPI_FUNCTION {
    DPI_SWITCH = 8
} typedef TYPE_DPI_FUNCTION;

enum TYPE_DISABLED_FUNCTION {
    DISABLED
} typedef TYPE_DISABLED_FUNCTION;

#endif