#ifndef ENUMS_H
#define ENUMS_H

enum MOUSE_REPORT {
    REPORT_CONNECTION           = 0x46,
    REPORT_HARDWARE             = 0x50,
    REPORT_HEARTBEAT            = 0x51,
    REPORT_ONBOARD_LED_SETTINGS = 0x52
} typedef MOUSE_REPORT;

enum MOUSE_BUTTON {
	LEFT_MOUSE_BUTTON,
	RIGHT_MOUSE_BUTTON,
	MIDDLE_MOUSE_BUTTON,
	SIDE_BUTTON_BACK,
	SIDE_BUTTON_FORWARD,
	DPI_BUTTON
} typedef MOUSE_BUTTON;

enum ASSIGNMENT_TYPE {
    DISABLED_FUNCTION,
	MOUSE_FUNCTION,
	KEYBOARD_FUNCTION,
	MEDIA_FUNCTION,
	MACRO_FUNCTION,
	DPI_FUNCTION = 0x07
} typedef ASSIGNMENT_TYPE;

enum TYPE_MOUSE_FUNCTION {
    LEFT_CLICK = 0x01,
    RIGHT_CLICK,
    MIDDLE_CLICK,
    BACK,
    FORWARD
} typedef TYPE_MOUSE_FUNCTION;

enum TYPE_KEYBOARD_FUNCTION {
    KEY_A = 0x04
} typedef TYPE_KEYBOARD_FUNCTION;

enum TYPE_MEDIA_FUNCTION {
    PLAY_PAUSE  = 0x00,
    STOP        = 0x01,
    PREVIOUS    = 0x02,
    NEXT        = 0x03,
    MUTE        = 0x04,
    VOLUME_DOWN = 0x05,
    VOLUME_UP   = 0x06,
} typedef TYPE_MEDIA_FUNCTION;

enum TYPE_DPI_FUNCTION {
    DPI_SWITCH = 0x08
} typedef TYPE_DPI_FUNCTION;

enum TYPE_DISABLED_FUNCTION {
    DISABLED
} typedef TYPE_DISABLED_FUNCTION;

enum SEND_BYTE {
    SEND_POLLING_RATE        = 0xd0,
    SEND_LOWER_POWER_WARNING = 0xd1, // TODO: verify value
    SEND_LED                 = 0xd2,
    SEND_DPI                 = 0xd3,
    SEND_BUTTON_ASSIGNMENT   = 0xd4,
    SEND_MACRO_ASSIGNMENT    = 0xd5,
    SEND_MACRO_DATA          = 0xd6,
    SAVE_SETTINGS            = 0xda
} typedef SEND_BYTE;

#endif