#!/usr/bin/env bash

BUILD_DIR=$1
if [[ -z $BUILD_DIR ]]; then
	BUILD_DIR=build
else
	BUILD_DIR=$(basename $BUILD_DIR)
fi

SOURCE_DIR=$2

grep() {
	pcre2grep $@
}

output-deps() {
	local filepath=$1
	
	local file=$(basename $filepath)
	local objfile="$BUILD_DIR/$(sed 's/\.c/\.o/m' <<< $file)"

	local deps=$(grep '#include\s"' $filepath)
	deps=$(sed -r "s/#include\s//g;s/\"//g" <<< $deps)

	REPLY=$deps
	[[ -z $REPLY ]] && return

	REPLY="$objfile: $deps"
	echo $REPLY >&2
	REPLY+="\n"
}

if [[ $1 == "--help" ]]; then
	echo "Usage: $(basename $0) build-dir source-dir-path";
	echo "build-dir:       The basename of the build directory. Defaults to 'build'."
	echo "source-dir-path: The path to search for source files. Defaults to the current working directory."
	exit -1
fi

SOURCE_FILES=$(find $SOURCE_DIR -name "*.c" | tr '\n' ' ')
DEPS=
for file in $SOURCE_FILES; do
	output-deps $file
	DEPS+=$REPLY
done

# Only echo dependencies to stdout when not runnnig the script directly (pipe, redirection, etc)
[[ ! -t 1 ]] && echo -e ${DEPS}