#ifndef MACRO_TYPES_H
#define MACRO_TYPES_H

#include "./device/buttons.h"

/**
 * @brief An enum for macro event pressed/released states.
 * 
 */
typedef enum MACRO_EVENT_TYPE {
	MACRO_EVENT_TYPE_UP   = 0x00,
	MACRO_EVENT_TYPE_DOWN = 0x01
} MACRO_EVENT_TYPE;

enum GENERIC_ACTION_EVENT_TYPES {
    KEY_DOWN   = (MACRO_ACTION_TYPE_KEYBOARD << 8) + MACRO_EVENT_TYPE_DOWN,
    KEY_UP     = (MACRO_ACTION_TYPE_KEYBOARD << 8) + MACRO_EVENT_TYPE_UP,
    MOUSE_DOWN = (MACRO_ACTION_TYPE_MOUSE    << 8) + MACRO_EVENT_TYPE_DOWN,
    MOUSE_UP   = (MACRO_ACTION_TYPE_MOUSE    << 8) + MACRO_EVENT_TYPE_UP
} typedef GENERIC_ACTION_EVENT_TYPES;

#endif
